export const dummy = [
	{
		id: 1,
		name: '서대원',
		department: '정보융합학부',
		email: 'ddww1029wwdd@gmail.com',
		role: 'member',
		signinData: '2024/12/01',
	},
	{
		id: 2,
		name: '서대원',
		department: '정보융합학부',
		email: 'ddww1029wwdd@gmail.com',
		role: 'student',
		signinData: '2024/12/01',
	},
	{
		id: 3,
		name: '고석환',
		department: '정보융합학부',
		email: 'ddww1029wwdd@gmail.com',
		role: 'member',
		signinData: '2024/12/01',
	},
	{
		id: 4,
		name: '고석환',
		department: '정보융합학부',
		email: 'ddww1029wwdd@gmail.com',
		role: 'student',
		signinData: '2024/12/01',
	},
	{
		id: 5,
		name: '고석환',
		department: '정보융합학부',
		email: 'ddww1029wwdd@gmail.com',
		role: 'student',
		signinData: '2024/12/01',
	},
	{
		id: 6,
		name: '고석환',
		department: '정보융합학부',
		email: 'ddww1029wwdd@gmail.com',
		role: 'student',
		signinData: '2024/12/01',
	},
	{
		id: 6,
		name: '고석환',
		department: '정보융합학부',
		email: 'ddww1029wwdd@gmail.com',
		role: 'student',
		signinData: '2024/12/01',
	},
	{
		id: 6,
		name: '고석환',
		department: '정보융합학부',
		email: 'ddww1029wwdd@gmail.com',
		role: 'student',
		signinData: '2024/12/01',
	},
	{
		id: 6,
		name: '고석환',
		department: '정보융합학부',
		email: 'ddww1029wwdd@gmail.com',
		role: 'student',
		signinData: '2024/12/01',
	},
	{
		id: 6,
		name: '고석환',
		department: '정보융합학부',
		email: 'ddww1029wwdd@gmail.com',
		role: 'student',
		signinData: '2024/12/01',
	},
	{
		id: 6,
		name: '고석환',
		department: '정보융합학부',
		email: 'ddww1029wwdd@gmail.com',
		role: 'student',
		signinData: '2024/12/01',
	},
	{
		id: 6,
		name: '고석환',
		department: '정보융합학부',
		email: 'ddww1029wwdd@gmail.com',
		role: 'student',
		signinData: '2024/12/01',
	},
	{
		id: 6,
		name: '고석환',
		department: '정보융합학부',
		email: 'ddww1029wwdd@gmail.com',
		role: 'student',
		signinData: '2024/12/01',
	},
	{
		id: 6,
		name: '고석환',
		department: '정보융합학부',
		email: 'ddww1029wwdd@gmail.com',
		role: 'student',
		signinData: '2024/12/01',
	},
];
